# Change these first
owner: wirewayproject # Your GitHub organization or username, where this repository lives
repo: uptime # The name

sites:
  - name: Proxy
    url: https://wireway.ch/api/status/nodes/?node=1
  - name: r-place.ch
    url: https://r-place.ch
  - name: r-place.ch Pocketbase
    url: https://pocketbase.r-place.ch/_/
  - name: Wireway Website
    url: https://wireway.ch
  - name: Wireway Speedtest
    url: https://speedtest.wireway.ch
  - name: Wireway Autoajax
    url: https://autoajax.wireway.ch
  - name: Wireway CLI
    url: https://wireway.ch/cli.html
  - name: obvTiger Website
    url: https://obvtiger.ch
  - name: MCServerSearch
    url: https://mcserversearch.com
  - name: eniv.app
    url: https://eniv.app
  - name: eniv.app Preview
    url: https://preview.eniv.app
  - name: CaveAttack
    url: https://caveattack.shield-break.net/
  - name: CaveAttack Map
    url: https://caveattack.shield-break.net/map/
  - name: Discardium
    url: https://discardium.com
  - name: Bubicloud
    url: https://cloud.bubicloud.ch
    expectedStatusCodes:
      - 200
      - 403



workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/30 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

status-website:
  cname: status.wireway.ch
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Wireway
  introTitle: "**Wireway** is a project operated by a single person making Websites"
  introMessage: Status page hosted by GitHub. Check out some of my projects at [wireway.ch](https://wireway.ch)
  navbar:
    - title: Status
      href: /
    - title: Wireway.ch
      href: https://wireway.ch
    - title: Speedtest
      href: https://speedtest.wireway.ch
